# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filterdesign_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FilterDesign(object):
    def setupUi(self, FilterDesign):
        FilterDesign.setObjectName("FilterDesign")
        FilterDesign.resize(1304, 709)
        self.fp_1_label = QtWidgets.QLabel(FilterDesign)
        self.fp_1_label.setGeometry(QtCore.QRect(20, 110, 72, 15))
        self.fp_1_label.setObjectName("fp_1_label")
        self.fst_1_label = QtWidgets.QLabel(FilterDesign)
        self.fst_1_label.setGeometry(QtCore.QRect(20, 190, 72, 15))
        self.fst_1_label.setObjectName("fst_1_label")
        self.verticalLayoutWidget = QtWidgets.QWidget(FilterDesign)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 270, 1251, 411))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.apply_button = QtWidgets.QPushButton(FilterDesign)
        self.apply_button.setGeometry(QtCore.QRect(1180, 130, 93, 28))
        self.apply_button.setObjectName("apply_button")
        self.confirm_button = QtWidgets.QPushButton(FilterDesign)
        self.confirm_button.setGeometry(QtCore.QRect(1180, 170, 93, 28))
        self.confirm_button.setObjectName("confirm_button")
        self.cancel_button = QtWidgets.QPushButton(FilterDesign)
        self.cancel_button.setGeometry(QtCore.QRect(1180, 210, 93, 28))
        self.cancel_button.setObjectName("cancel_button")
        self.typeof_filt = QtWidgets.QLabel(FilterDesign)
        self.typeof_filt.setGeometry(QtCore.QRect(20, 30, 72, 15))
        self.typeof_filt.setObjectName("typeof_filt")
        self.band_type_combo = QtWidgets.QComboBox(FilterDesign)
        self.band_type_combo.setGeometry(QtCore.QRect(20, 50, 91, 41))
        self.band_type_combo.setObjectName("band_type_combo")
        self.fst_2_label = QtWidgets.QLabel(FilterDesign)
        self.fst_2_label.setGeometry(QtCore.QRect(120, 190, 72, 15))
        self.fst_2_label.setObjectName("fst_2_label")
        self.fp_2_label = QtWidgets.QLabel(FilterDesign)
        self.fp_2_label.setGeometry(QtCore.QRect(120, 110, 72, 15))
        self.fp_2_label.setObjectName("fp_2_label")
        self.sample_rate_label = QtWidgets.QLabel(FilterDesign)
        self.sample_rate_label.setGeometry(QtCore.QRect(320, 30, 91, 16))
        self.sample_rate_label.setObjectName("sample_rate_label")
        self.FIR_IRR_type_combo = QtWidgets.QComboBox(FilterDesign)
        self.FIR_IRR_type_combo.setGeometry(QtCore.QRect(120, 50, 91, 41))
        self.FIR_IRR_type_combo.setObjectName("FIR_IRR_type_combo")
        self.FIR_type_combo = QtWidgets.QComboBox(FilterDesign)
        self.FIR_type_combo.setGeometry(QtCore.QRect(220, 50, 91, 41))
        self.FIR_type_combo.setObjectName("FIR_type_combo")
        self.IRR_type_combo = QtWidgets.QComboBox(FilterDesign)
        self.IRR_type_combo.setGeometry(QtCore.QRect(220, 50, 91, 41))
        self.IRR_type_combo.setObjectName("IRR_type_combo")
        self.gstop_label = QtWidgets.QLabel(FilterDesign)
        self.gstop_label.setGeometry(QtCore.QRect(220, 190, 72, 15))
        self.gstop_label.setObjectName("gstop_label")
        self.gpass_label = QtWidgets.QLabel(FilterDesign)
        self.gpass_label.setGeometry(QtCore.QRect(220, 110, 72, 15))
        self.gpass_label.setObjectName("gpass_label")
        self.cheby_rs = QtWidgets.QLabel(FilterDesign)
        self.cheby_rs.setGeometry(QtCore.QRect(320, 110, 72, 15))
        self.cheby_rs.setObjectName("cheby_rs")
        self.cheby_rp = QtWidgets.QLabel(FilterDesign)
        self.cheby_rp.setGeometry(QtCore.QRect(320, 190, 72, 15))
        self.cheby_rp.setObjectName("cheby_rp")
        self.rp_line = QtWidgets.QLineEdit(FilterDesign)
        self.rp_line.setGeometry(QtCore.QRect(320, 210, 91, 41))
        self.rp_line.setObjectName("rp_line")
        self.rs_line = QtWidgets.QLineEdit(FilterDesign)
        self.rs_line.setGeometry(QtCore.QRect(320, 130, 91, 41))
        self.rs_line.setObjectName("rs_line")
        self.gpass_line = QtWidgets.QLineEdit(FilterDesign)
        self.gpass_line.setGeometry(QtCore.QRect(220, 130, 91, 41))
        self.gpass_line.setObjectName("gpass_line")
        self.gstop_line = QtWidgets.QLineEdit(FilterDesign)
        self.gstop_line.setGeometry(QtCore.QRect(220, 210, 91, 41))
        self.gstop_line.setObjectName("gstop_line")
        self.fst_2_line = QtWidgets.QLineEdit(FilterDesign)
        self.fst_2_line.setGeometry(QtCore.QRect(120, 210, 91, 41))
        self.fst_2_line.setObjectName("fst_2_line")
        self.fp_2_line = QtWidgets.QLineEdit(FilterDesign)
        self.fp_2_line.setGeometry(QtCore.QRect(120, 130, 91, 41))
        self.fp_2_line.setObjectName("fp_2_line")
        self.fst_1_line = QtWidgets.QLineEdit(FilterDesign)
        self.fst_1_line.setGeometry(QtCore.QRect(20, 210, 91, 41))
        self.fst_1_line.setObjectName("fst_1_line")
        self.fp_1_line = QtWidgets.QLineEdit(FilterDesign)
        self.fp_1_line.setGeometry(QtCore.QRect(20, 130, 91, 41))
        self.fp_1_line.setObjectName("fp_1_line")
        self.sample_rate_line = QtWidgets.QLineEdit(FilterDesign)
        self.sample_rate_line.setGeometry(QtCore.QRect(320, 50, 91, 41))
        self.sample_rate_line.setObjectName("sample_rate_line")
        self.horizontalLayoutWidget = QtWidgets.QWidget(FilterDesign)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(430, 20, 741, 231))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.retranslateUi(FilterDesign)
        QtCore.QMetaObject.connectSlotsByName(FilterDesign)

    def retranslateUi(self, FilterDesign):
        _translate = QtCore.QCoreApplication.translate
        FilterDesign.setWindowTitle(_translate("FilterDesign", "Filter Design"))
        self.fp_1_label.setText(_translate("FilterDesign", "fp_1"))
        self.fst_1_label.setText(_translate("FilterDesign", "fst_1"))
        self.apply_button.setText(_translate("FilterDesign", "apply"))
        self.confirm_button.setText(_translate("FilterDesign", "confirm"))
        self.cancel_button.setText(_translate("FilterDesign", "cancel"))
        self.typeof_filt.setText(_translate("FilterDesign", "type"))
        self.fst_2_label.setText(_translate("FilterDesign", "fst_2"))
        self.fp_2_label.setText(_translate("FilterDesign", "fp_2"))
        self.sample_rate_label.setText(_translate("FilterDesign", "sample_rate"))
        self.gstop_label.setText(_translate("FilterDesign", "gstop"))
        self.gpass_label.setText(_translate("FilterDesign", "gpass"))
        self.cheby_rs.setText(_translate("FilterDesign", "rs"))
        self.cheby_rp.setText(_translate("FilterDesign", "rp"))
