# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filterdesign_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FilterDesign(object):
    def setupUi(self, FilterDesign):
        FilterDesign.setObjectName("FilterDesign")
        FilterDesign.resize(625, 528)
        self.fp_1_label = QtWidgets.QLabel(FilterDesign)
        self.fp_1_label.setGeometry(QtCore.QRect(20, 110, 72, 15))
        self.fp_1_label.setObjectName("fp_1_label")
        self.fp_1_text = QtWidgets.QTextBrowser(FilterDesign)
        self.fp_1_text.setGeometry(QtCore.QRect(20, 130, 91, 41))
        self.fp_1_text.setReadOnly(False)
        self.fp_1_text.setObjectName("fp_1_text")
        self.fst_1_label = QtWidgets.QLabel(FilterDesign)
        self.fst_1_label.setGeometry(QtCore.QRect(20, 190, 72, 15))
        self.fst_1_label.setObjectName("fst_1_label")
        self.fst_1_text = QtWidgets.QTextBrowser(FilterDesign)
        self.fst_1_text.setGeometry(QtCore.QRect(20, 210, 91, 41))
        self.fst_1_text.setReadOnly(False)
        self.fst_1_text.setObjectName("fst_1_text")
        self.verticalLayoutWidget = QtWidgets.QWidget(FilterDesign)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 270, 591, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.apply_button = QtWidgets.QPushButton(FilterDesign)
        self.apply_button.setGeometry(QtCore.QRect(520, 130, 93, 28))
        self.apply_button.setObjectName("apply_button")
        self.confirm_button = QtWidgets.QPushButton(FilterDesign)
        self.confirm_button.setGeometry(QtCore.QRect(520, 170, 93, 28))
        self.confirm_button.setObjectName("confirm_button")
        self.cancel_button = QtWidgets.QPushButton(FilterDesign)
        self.cancel_button.setGeometry(QtCore.QRect(520, 210, 93, 28))
        self.cancel_button.setObjectName("cancel_button")
        self.typeof_filt = QtWidgets.QLabel(FilterDesign)
        self.typeof_filt.setGeometry(QtCore.QRect(20, 30, 72, 15))
        self.typeof_filt.setObjectName("typeof_filt")
        self.band_type_combo = QtWidgets.QComboBox(FilterDesign)
        self.band_type_combo.setGeometry(QtCore.QRect(20, 50, 91, 41))
        self.band_type_combo.setObjectName("band_type_combo")
        self.fst_2_label = QtWidgets.QLabel(FilterDesign)
        self.fst_2_label.setGeometry(QtCore.QRect(120, 190, 72, 15))
        self.fst_2_label.setObjectName("fst_2_label")
        self.fp_2_text = QtWidgets.QTextBrowser(FilterDesign)
        self.fp_2_text.setGeometry(QtCore.QRect(120, 130, 91, 41))
        self.fp_2_text.setReadOnly(False)
        self.fp_2_text.setObjectName("fp_2_text")
        self.fst_2_text = QtWidgets.QTextBrowser(FilterDesign)
        self.fst_2_text.setGeometry(QtCore.QRect(120, 210, 91, 41))
        self.fst_2_text.setReadOnly(False)
        self.fst_2_text.setObjectName("fst_2_text")
        self.fp_2_label = QtWidgets.QLabel(FilterDesign)
        self.fp_2_label.setGeometry(QtCore.QRect(120, 110, 72, 15))
        self.fp_2_label.setObjectName("fp_2_label")
        self.sample_rate_text = QtWidgets.QTextBrowser(FilterDesign)
        self.sample_rate_text.setGeometry(QtCore.QRect(320, 50, 191, 41))
        self.sample_rate_text.setReadOnly(False)
        self.sample_rate_text.setObjectName("sample_rate_text")
        self.sample_rate_label = QtWidgets.QLabel(FilterDesign)
        self.sample_rate_label.setGeometry(QtCore.QRect(320, 30, 91, 16))
        self.sample_rate_label.setObjectName("sample_rate_label")
        self.FIR_IRR_type_combo = QtWidgets.QComboBox(FilterDesign)
        self.FIR_IRR_type_combo.setGeometry(QtCore.QRect(120, 50, 91, 41))
        self.FIR_IRR_type_combo.setObjectName("FIR_IRR_type_combo")
        self.FIR_type_combo = QtWidgets.QComboBox(FilterDesign)
        self.FIR_type_combo.setGeometry(QtCore.QRect(220, 50, 91, 41))
        self.FIR_type_combo.setObjectName("FIR_type_combo")
        self.IRR_type_combo = QtWidgets.QComboBox(FilterDesign)
        self.IRR_type_combo.setGeometry(QtCore.QRect(220, 50, 91, 41))
        self.IRR_type_combo.setObjectName("IRR_type_combo")
        self.As_text = QtWidgets.QTextBrowser(FilterDesign)
        self.As_text.setGeometry(QtCore.QRect(220, 210, 91, 41))
        self.As_text.setReadOnly(False)
        self.As_text.setObjectName("As_text")
        self.As_label = QtWidgets.QLabel(FilterDesign)
        self.As_label.setGeometry(QtCore.QRect(220, 190, 72, 15))
        self.As_label.setObjectName("As_label")
        self.Rp_text = QtWidgets.QTextBrowser(FilterDesign)
        self.Rp_text.setGeometry(QtCore.QRect(220, 130, 91, 41))
        self.Rp_text.setReadOnly(False)
        self.Rp_text.setObjectName("Rp_text")
        self.Rp_label = QtWidgets.QLabel(FilterDesign)
        self.Rp_label.setGeometry(QtCore.QRect(220, 110, 72, 15))
        self.Rp_label.setObjectName("Rp_label")

        self.retranslateUi(FilterDesign)
        QtCore.QMetaObject.connectSlotsByName(FilterDesign)

    def retranslateUi(self, FilterDesign):
        _translate = QtCore.QCoreApplication.translate
        FilterDesign.setWindowTitle(_translate("FilterDesign", "Filter Design"))
        self.fp_1_label.setText(_translate("FilterDesign", "fp_1"))
        self.fst_1_label.setText(_translate("FilterDesign", "fst_1"))
        self.apply_button.setText(_translate("FilterDesign", "apply"))
        self.confirm_button.setText(_translate("FilterDesign", "confirm"))
        self.cancel_button.setText(_translate("FilterDesign", "cancel"))
        self.typeof_filt.setText(_translate("FilterDesign", "type"))
        self.fst_2_label.setText(_translate("FilterDesign", "fst_2"))
        self.fp_2_label.setText(_translate("FilterDesign", "fp_2"))
        self.sample_rate_label.setText(_translate("FilterDesign", "sample_rate"))
        self.As_label.setText(_translate("FilterDesign", "As"))
        self.Rp_label.setText(_translate("FilterDesign", "Rp"))
